# Generated by Django 5.2.4 on 2025-09-24 17:58

# Dentro do novo ficheiro de migração (ex: 0002_auto_....py)

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    ADMIN_USER = os.environ.get('ADMIN_USER')
    ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL')
    ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')

    if ADMIN_USER and ADMIN_EMAIL and ADMIN_PASSWORD:
        if not User.objects.filter(username=ADMIN_USER).exists():
            User.objects.create_superuser(
                username=ADMIN_USER,
                email=ADMIN_EMAIL,
                password=ADMIN_PASSWORD
            )
            print(f"Superuser '{ADMIN_USER}' created.")
        else:
            print(f"Superuser '{ADMIN_USER}' already exists.")

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'), 
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]