# Generated by Django 5.2.4 on 2025-09-24 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('danificado', 'Danificado')], default='disponivel', max_length=15, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exemplares',
            },
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade_total', models.IntegerField()),
                ('valor_emprestimo_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_dias_emprestimo', models.IntegerField(blank=True, default=None, null=True)),
                ('permite_renovacao', models.BooleanField(default=True)),
                ('multa_atraso_multiplicador', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('multa_dano_multiplicador', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='recurso_capas/')),
            ],
            options={
                'db_table': 'recursos',
            },
        ),
        migrations.CreateModel(
            name='Subtipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_subtipo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='subtipo_imagens/')),
            ],
            options={
                'db_table': 'subtipos',
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField()),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao_efetiva', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.clientes')),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos.exemplares')),
            ],
            options={
                'db_table': 'emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_multa', models.CharField(max_length=10)),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paga', models.IntegerField(blank=True, null=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos.emprestimos')),
            ],
            options={
                'db_table': 'multas',
            },
        ),
        migrations.AddField(
            model_name='exemplares',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos.recursos'),
        ),
        migrations.CreateModel(
            name='Renovacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_renovacao', models.DateTimeField(blank=True, null=True)),
                ('nova_data_prevista_devolucao', models.DateField()),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos.emprestimos')),
            ],
            options={
                'db_table': 'renovacoes',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(blank=True, null=True)),
                ('data_inicio_reserva', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.clientes')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos.recursos')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.AddField(
            model_name='recursos',
            name='subtipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos.subtipos'),
        ),
        migrations.AddField(
            model_name='subtipos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos.tipos'),
        ),
        migrations.AddField(
            model_name='recursos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recursos.tipos'),
        ),
    ]
